Add hammerspoon and associated configuration files

diff --git a/script/strap-after-setup b/script/strap-after-setup
--- a/script/strap-after-setup
+++ b/script/strap-after-setup
@@ -14,7 +14,29 @@ set -e
 mkdir -p ~/Library/Application\ Support/Spectacle
 ln -sfn ~/.dotfiles/programs/spectacle/shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json
 
-# Visual Studio Code
+# Hammerspoon
+hammerspoondir=~/.hammerspoon
+mkdir -p $hammerspoondir
+echo "dowloading the Lunette spoon"
+# download and copy over Lunette spoon
+git clone git@github.com:scottwhudson/Lunette.git &> /dev/null
+if [[ $? -eq 128 ]]; then
+    echo "spoon repo already exists."
+elif [[ $? -eq 0 ]]; then
+    echo "Cloned spoon repo."
+else
+    echo "Failed to clone spoon repo."
+fi
+spoonsdir="$hammerspoondir/Spoons"
+echo $spoonsdir
+mkdir -p $spoonsdir
+cp -R Lunette/Source/Lunette.spoon $spoonsdir
+rm -rf Lunette
+
+# symlink the init.lua
+ln -sfn ~/.dotfiles/programs/hammerspoon/init.lua "$hammerspoondir/init.lua"
+
+# # Visual Studio Code
 mkdir -p ~/Library/Application\ Support/Code/User
 for f in $(ls -d ~/.dotfiles/programs/code/*.json); do ln -sfn $f ~/Library/Application\ Support/Code/User/$(basename $f); done
 # install extensions
